// Code generated by MockGen. DO NOT EDIT.
// Source: verifier.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNetworkUtils is a mock of NetworkUtils interface.
type MockNetworkUtils struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkUtilsMockRecorder
}

// MockNetworkUtilsMockRecorder is the mock recorder for MockNetworkUtils.
type MockNetworkUtilsMockRecorder struct {
	mock *MockNetworkUtils
}

// NewMockNetworkUtils creates a new mock instance.
func NewMockNetworkUtils(ctrl *gomock.Controller) *MockNetworkUtils {
	mock := &MockNetworkUtils{ctrl: ctrl}
	mock.recorder = &MockNetworkUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkUtils) EXPECT() *MockNetworkUtilsMockRecorder {
	return m.recorder
}

// DoesHostnameResolveBackToIP mocks base method.
func (m *MockNetworkUtils) DoesHostnameResolveBackToIP(ipAddress, hostname string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoesHostnameResolveBackToIP", ipAddress, hostname)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DoesHostnameResolveBackToIP indicates an expected call of DoesHostnameResolveBackToIP.
func (mr *MockNetworkUtilsMockRecorder) DoesHostnameResolveBackToIP(ipAddress, hostname interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoesHostnameResolveBackToIP", reflect.TypeOf((*MockNetworkUtils)(nil).DoesHostnameResolveBackToIP), ipAddress, hostname)
}

// GetASN mocks base method.
func (m *MockNetworkUtils) GetASN(ipAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetASN", ipAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetASN indicates an expected call of GetASN.
func (mr *MockNetworkUtilsMockRecorder) GetASN(ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetASN", reflect.TypeOf((*MockNetworkUtils)(nil).GetASN), ipAddress)
}

// GetHosts mocks base method.
func (m *MockNetworkUtils) GetHosts(ipAddress string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHosts", ipAddress)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetHosts indicates an expected call of GetHosts.
func (mr *MockNetworkUtilsMockRecorder) GetHosts(ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHosts", reflect.TypeOf((*MockNetworkUtils)(nil).GetHosts), ipAddress)
}
